# This workflow works by removing a "Needs QA" label from a PR when the actor is
# a dependabot user. It runs when a PR is merged.
#
# We need this mechanism to allow for automerging whitelisted dependencies while
# also allowing for blocking a merge to master for deployment (in the way that
# our other PRs work).
name: Remove 'Needs QA' label for auto-merged PRs.
on:
  pull_request:
    types: [closed]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    if: >
      (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
      && github.event.pull_request.merged

    steps:
      - name: Remove QA Label
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{ secrets.PANORAMA_BOT_TOKEN }}
          script: |
            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Needs QA'
            })
