name: Dependabot Pull Request
on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: Fetch Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v1.1.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Approve and merge Dependabot PRs for development dependencies
      # Merge the PR if either:
      # a) it has the `development-dependencies` label, which we add for certain
      #    categories of PRs (see `.github/dependabot.yml`), OR
      # b) Dependabot has categorized it as a `direct:development` dependency,
      #    meaning it's in the Gemfile in a `development` or `test` group
      if: ${{ contains(github.event.pull_request.labels.*.name, 'development-dependencies') || steps.dependabot-metadata.outputs.dependency-type == 'direct:development' }}
      run: gh pr merge --auto --merge "$PR_URL" && gh pr edit "$PR_URL" --remove-label "Needs QA" && gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.PANORAMA_BOT_RW_TOKEN}}
