# This workflow works by running steps for the action when the github actor is a
# dependabot user. It runs on the opening of a PR.
#
# The first step is an auto-approve action, which allows dependabot to
# auto-merge a PR and for us to continue requiring an approval to merge. The
# second step automatically assigns a squad to review the ticket.
name: Triage dependabot tickets to squads for review
on:
  pull_request:
    types: [opened]

jobs:
  dependabot-triage:
    runs-on: ubuntu-latest
    if: (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')

    steps:
      - name: Auto-approve for dependabot
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.PANORAMA_BOT_TOKEN }}"

      - name: Assign to squad for review
        uses: panorama-ed/triage-review-to-team@master
        with:
          # See LastPass for this token
          github-token: "${{ secrets.PANORAMA_BOT_TOKEN }}"
